namespace Wexflow.Core.Db.Firebird
{
    public class Approver : Core.Db.Approver
    {
        public const string ColumnNameId = "ID";
        public const string ColumnNameUserId = "USER_ID";
        public const string ColumnNameRecordId = "RECORD_ID";
        public const string ColumnNameApproved = "APPROVED";
        public const string ColumnNameApprovedOn = "APPROVED_ON";

        public const string TableStruct = "(" + ColumnNameId + " integer generated by default as identity primary key, "
                                                        + ColumnNameUserId + " INTEGER, "
                                                        + ColumnNameRecordId + " INTEGER, "
                                                        + ColumnNameApproved + " BOOLEAN, "
                                                        + ColumnNameApprovedOn + " TIMESTAMP)";

        public int Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
