namespace Wexflow.Core.Db.Firebird
{
    public class Notification : Core.Db.Notification
    {
        public const string ColumnNameId = "ID";
        public const string ColumnNameAssignedBy = "ASSIGNED_BY";
        public const string ColumnNameAssignedOn = "ASSIGNED_ON";
        public const string ColumnNameAssignedTo = "ASSIGNED_TO";
        public const string ColumnNameMessage = "MESSAGE";
        public const string ColumnNameIsRead = "IS_READ";

        public const string TableStruct = "(" + ColumnNameId + " integer generated by default as identity primary key, "
                                                        + ColumnNameAssignedBy + " INTEGER, "
                                                        + ColumnNameAssignedOn + " TIMESTAMP, "
                                                        + ColumnNameAssignedTo + " INTEGER, "
                                                        + ColumnNameMessage + " BLOB SUB_TYPE TEXT, "
                                                        + ColumnNameIsRead + " BOOLEAN)";

        public int Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
