namespace Wexflow.Core.Db.Firebird
{
    public class Record : Core.Db.Record
    {
        public const string ColumnName_Id = "ID";
        public const string ColumnName_Name = "NAME";
        public const string ColumnName_Description = "DESCRIPTION";
        public const string ColumnName_Approved = "APPROVED";
        public const string ColumnName_StartDate = "START_DATE";
        public const string ColumnName_EndDate = "END_DATE";
        public const string ColumnName_Comments = "COMMENTS";
        public const string ColumnName_ManagerComments = "MANAGER_COMMENTS";
        public const string ColumnName_CreatedBy = "CREATED_BY";
        public const string ColumnName_CreatedOn = "CREATED_ON";
        public const string ColumnName_ModifiedBy = "MODIFIED_BY";
        public const string ColumnName_ModifiedOn = "MODIFIED_ON";
        public const string ColumnName_AssignedTo = "ASSIGNED_TO";
        public const string ColumnName_AssignedOn = "ASSIGNED_ON";

        public const string TableStruct = "(" + ColumnName_Id + " integer generated by default as identity primary key, "
                                                        + ColumnName_Name + " VARCHAR(512), "
                                                        + ColumnName_Description + " BLOB SUB_TYPE TEXT, "
                                                        + ColumnName_Approved + " BOOLEAN, "
                                                        + ColumnName_StartDate + " TIMESTAMP, "
                                                        + ColumnName_EndDate + " TIMESTAMP, "
                                                        + ColumnName_Comments + " BLOB SUB_TYPE TEXT, "
                                                        + ColumnName_ManagerComments + " BLOB SUB_TYPE TEXT, "
                                                        + ColumnName_CreatedBy + " INTEGER, "
                                                        + ColumnName_CreatedOn + " TIMESTAMP, "
                                                        + ColumnName_ModifiedBy + " INTEGER, "
                                                        + ColumnName_ModifiedOn + " TIMESTAMP, "
                                                        + ColumnName_AssignedTo + " INTEGER, "
                                                        + ColumnName_AssignedOn + " TIMESTAMP)";

        public int Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
