namespace Wexflow.Core.Db.Firebird
{
    public class Workflow : Core.Db.Workflow
    {
        public const string COLUMN_NAME_ID = "ID";
        public const string COLUMN_NAME_XML = "XML";

        public const string TABLE_STRUCT = "(" + COLUMN_NAME_ID + " integer generated by default as identity primary key, " + COLUMN_NAME_XML + " BLOB SUB_TYPE TEXT)";

        public int Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
