namespace Wexflow.Core.Db.Firebird
{
    public class UserWorkflow : Core.Db.UserWorkflow
    {
        public const string ColumnNameId = "ID";
        public const string ColumnNameUserId = "USER_ID";
        public const string ColumnNameWorkflowId = "WORKFLOW_ID";

        public const string TableStruct = "(" + ColumnNameId + " integer generated by default as identity primary key, " + ColumnNameUserId + " INTEGER, " + ColumnNameWorkflowId + " INTEGER)";

        public string Id { get; set; }
    }
}
