namespace Wexflow.Core.Db.Firebird
{
    public class Workflow : Core.Db.Workflow
    {
        public const string ColumnNameId = "ID";
        public const string ColumnNameXml = "XML";

        public const string TableStruct = "(" + ColumnNameId + " integer generated by default as identity primary key, " + ColumnNameXml + " BLOB SUB_TYPE TEXT)";

        public int Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
