call uglify-login.bat
call uglify-forgot-password.bat
call uglify-dashboard.bat
call uglify-records.bat
call uglify-manager.bat
call uglify-approval.bat
::call uglify-editor.bat
call uglify-designer.bat
call uglify-history.bat
call uglify-users.bat
call uglify-profiles.bat
call uglify-notifications.bat