namespace Wexflow.Core.Db.Oracle
{
    public class Approver : Core.Db.Approver
    {
        public const string COLUMN_NAME_ID = "ID";
        public const string COLUMN_NAME_USER_ID = "USER_ID";
        public const string COLUMN_NAME_RECORD_ID = "RECORD_ID";
        public const string COLUMN_NAME_APPROVED = "APPROVED";
        public const string COLUMN_NAME_APPROVED_ON = "APPROVED_ON";

        public const string TABLE_STRUCT = "(" + COLUMN_NAME_ID + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                                                        + COLUMN_NAME_USER_ID + " INTEGER, "
                                                        + COLUMN_NAME_RECORD_ID + " INTEGER, "
                                                        + COLUMN_NAME_APPROVED + " NUMBER(1), "
                                                        + COLUMN_NAME_APPROVED_ON + " TIMESTAMP)";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
