namespace Wexflow.Core.Db.Oracle
{
    public class Entry : Core.Db.Entry
    {
        public const string ColumnName_Id = "ID";
        public const string ColumnName_Name = "NAME";
        public const string ColumnName_Description = "DESCRIPTION";
        public const string ColumnName_LaunchType = "LAUNCH_TYPE";
        public const string ColumnName_StatusDate = "STATUS_DATE";
        public const string ColumnName_Status = "STATUS";
        public const string ColumnName_WorkflowId = "WORKFLOW_ID";
        public const string ColumnName_JobId = "JOB_ID";
        public const string ColumnName_Logs = "LOGS";

        public const string TableStruct = "(" + ColumnName_Id + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + ColumnName_Name + " VARCHAR2(255), " + ColumnName_Description + " VARCHAR2(255), " + ColumnName_LaunchType + " INTEGER, " + ColumnName_StatusDate + " TIMESTAMP, " + ColumnName_Status + " INTEGER, " + ColumnName_WorkflowId + " INTEGER, " + ColumnName_JobId + " VARCHAR2(255), " + ColumnName_Logs + " CLOB)";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
