namespace Wexflow.Core.Db.Oracle
{
    public class Entry : Core.Db.Entry
    {
        public const string ColumnNameId = "ID";
        public const string ColumnNameName = "NAME";
        public const string ColumnNameDescription = "DESCRIPTION";
        public const string ColumnNameLaunchType = "LAUNCH_TYPE";
        public const string ColumnNameStatusDate = "STATUS_DATE";
        public const string ColumnNameStatus = "STATUS";
        public const string ColumnNameWorkflowId = "WORKFLOW_ID";
        public const string ColumnNameJobId = "JOB_ID";
        public const string ColumnNameLogs = "LOGS";

        public const string TableStruct = "(" + ColumnNameId + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + ColumnNameName + " VARCHAR2(255), " + ColumnNameDescription + " VARCHAR2(255), " + ColumnNameLaunchType + " INTEGER, " + ColumnNameStatusDate + " TIMESTAMP, " + ColumnNameStatus + " INTEGER, " + ColumnNameWorkflowId + " INTEGER, " + ColumnNameJobId + " VARCHAR2(255), " + ColumnNameLogs + " CLOB)";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
