namespace Wexflow.Core.Db.Oracle
{
    public class Notification : Core.Db.Notification
    {
        public const string ColumnNameId = "ID";
        public const string ColumnNameAssignedBy = "ASSIGNED_BY";
        public const string ColumnNameAssignedOn = "ASSIGNED_ON";
        public const string ColumnNameAssignedTo = "ASSIGNED_TO";
        public const string ColumnNameMessage = "MESSAGE";
        public const string ColumnNameIsRead = "IS_READ";

        public const string TableStruct = "(" + ColumnNameId + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                                                        + ColumnNameAssignedBy + " INTEGER, "
                                                        + ColumnNameAssignedOn + " TIMESTAMP, "
                                                        + ColumnNameAssignedTo + " INTEGER, "
                                                        + ColumnNameMessage + " VARCHAR2(4000), "
                                                        + ColumnNameIsRead + " NUMBER(1))";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
