namespace Wexflow.Core.Db.Oracle
{
    public class Record : Core.Db.Record
    {
        public const string COLUMN_NAME_ID = "ID";
        public const string COLUMN_NAME_NAME = "NAME";
        public const string COLUMN_NAME_DESCRIPTION = "DESCRIPTION";
        public const string COLUMN_NAME_APPROVED = "APPROVED";
        public const string COLUMN_NAME_START_DATE = "START_DATE";
        public const string COLUMN_NAME_END_DATE = "END_DATE";
        public const string COLUMN_NAME_COMMENTS = "COMMENTS";
        public const string COLUMN_NAME_MANAGER_COMMENTS = "MANAGER_COMMENTS";
        public const string COLUMN_NAME_CREATED_BY = "CREATED_BY";
        public const string COLUMN_NAME_CREATED_ON = "CREATED_ON";
        public const string COLUMN_NAME_MODIFIED_BY = "MODIFIED_BY";
        public const string COLUMN_NAME_MODIFIED_ON = "MODIFIED_ON";
        public const string COLUMN_NAME_ASSIGNED_TO = "ASSIGNED_TO";
        public const string COLUMN_NAME_ASSIGNED_ON = "ASSIGNED_ON";

        public const string TABLE_STRUCT = "(" + COLUMN_NAME_ID + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                                                        + COLUMN_NAME_NAME + " VARCHAR2(512), "
                                                        + COLUMN_NAME_DESCRIPTION + " VARCHAR2(4000), "
                                                        + COLUMN_NAME_APPROVED + " NUMBER(1), "
                                                        + COLUMN_NAME_START_DATE + " TIMESTAMP, "
                                                        + COLUMN_NAME_END_DATE + " TIMESTAMP, "
                                                        + COLUMN_NAME_COMMENTS + " VARCHAR2(4000), "
                                                        + COLUMN_NAME_MANAGER_COMMENTS + " VARCHAR2(4000), "
                                                        + COLUMN_NAME_CREATED_BY + " INTEGER, "
                                                        + COLUMN_NAME_CREATED_ON + " TIMESTAMP, "
                                                        + COLUMN_NAME_MODIFIED_BY + " INTEGER, "
                                                        + COLUMN_NAME_MODIFIED_ON + " TIMESTAMP, "
                                                        + COLUMN_NAME_ASSIGNED_TO + " INTEGER, "
                                                        + COLUMN_NAME_ASSIGNED_ON + " TIMESTAMP)";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
