namespace Wexflow.Core.Db.Oracle
{
    public class StatusCount : Core.Db.StatusCount
    {
        public const string ColumnName_Id = "ID";
        public const string ColumnName_PendingCount = "PENDING_COUNT";
        public const string ColumnName_RunningCount = "RUNNING_COUNT";
        public const string ColumnName_DoneCount = "DONE_COUNT";
        public const string ColumnName_FailedCount = "FAILED_COUNT";
        public const string ColumnName_WarningCount = "WARNING_COUNT";
        public const string ColumnName_DisabledCount = "DISABLED_COUNT";
        public const string ColumnName_StoppedCount = "STOPPED_COUNT";
        public const string ColumnName_RejectedCount = "DISAPPROVED_COUNT";

        public const string TableStruct = "(" + ColumnName_Id + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + ColumnName_PendingCount + " INTEGER, " + ColumnName_RunningCount + " INTEGER, " + ColumnName_DoneCount + " INTEGER, " + ColumnName_FailedCount + " INTEGER, " + ColumnName_WarningCount + " INTEGER, " + ColumnName_DisabledCount + " INTEGER, " + ColumnName_StoppedCount + " INTEGER, " + ColumnName_RejectedCount + " INTEGER)";

        public long Id { get; set; }
    }
}