namespace Wexflow.Core.Db.Oracle
{
    public class User : Core.Db.User
    {
        public const string ColumnName_Id = "ID";
        public const string ColumnName_Username = "USERNAME";
        public const string ColumnName_Password = "PASSWORD";
        public const string ColumnName_UserProfile = "USER_PROFILE";
        public const string ColumnName_Email = "EMAIL";
        public const string ColumnName_CreatedOn = "CREATED_ON";
        public const string ColumnName_ModifiedOn = "MODIFIED_ON";

        public const string TableStruct = "(" + ColumnName_Id + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + ColumnName_Username + " VARCHAR2(255), " + ColumnName_Password + " VARCHAR2(255), " + ColumnName_UserProfile + " INTEGER, " + ColumnName_Email + " VARCHAR2(255), " + ColumnName_CreatedOn + " TIMESTAMP, " + ColumnName_ModifiedOn + " TIMESTAMP)";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
