namespace Wexflow.Core.Db.Oracle
{
    public class UserWorkflow : Core.Db.UserWorkflow
    {
        public const string ColumnNameId = "ID";
        public const string ColumnNameUserId = "USER_ID";
        public const string ColumnNameWorkflowId = "WORKFLOW_ID";

        public const string TableStruct = "(" + ColumnNameId + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + ColumnNameUserId + " INTEGER, " + ColumnNameWorkflowId + " INTEGER)";

        public string Id { get; set; }
    }
}
