namespace Wexflow.Core.Db.Oracle
{
    public class Version : Core.Db.Version
    {
        public const string COLUMN_NAME_ID = "ID";
        public const string COLUMN_NAME_RECORD_ID = "RECORD_ID";
        public const string COLUMN_NAME_FILE_PATH = "FILE_PATH";
        public const string COLUMN_NAME_CREATED_ON = "CREATED_ON";

        public const string TABLE_STRUCT = "(" + COLUMN_NAME_ID + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                                                        + COLUMN_NAME_RECORD_ID + " INTEGER, "
                                                        + COLUMN_NAME_FILE_PATH + " VARCHAR2(1024), "
                                                        + COLUMN_NAME_CREATED_ON + " TIMESTAMP)";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
