namespace Wexflow.Core.Db.Oracle
{
    public class Workflow : Core.Db.Workflow
    {
        public const string COLUMN_NAME_ID = "ID";
        public const string COLUMN_NAME_XML = "XML";

        public const string TABLE_STRUCT = "(" + COLUMN_NAME_ID + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + COLUMN_NAME_XML + " CLOB)";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
