namespace Wexflow.Core.Db.Oracle
{
    public class Approver : Core.Db.Approver
    {
        public const string ColumnNameId = "ID";
        public const string ColumnNameUserId = "USER_ID";
        public const string ColumnNameRecordId = "RECORD_ID";
        public const string ColumnNameApproved = "APPROVED";
        public const string ColumnNameApprovedOn = "APPROVED_ON";

        public const string TableStruct = "(" + ColumnNameId + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                                                        + ColumnNameUserId + " INTEGER, "
                                                        + ColumnNameRecordId + " INTEGER, "
                                                        + ColumnNameApproved + " NUMBER(1), "
                                                        + ColumnNameApprovedOn + " TIMESTAMP)";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
