namespace Wexflow.Core.Db.Oracle
{
    public class Notification : Core.Db.Notification
    {
        public static readonly string ColumnName_Id = "ID";
        public static readonly string ColumnName_AssignedBy = "ASSIGNED_BY";
        public static readonly string ColumnName_AssignedOn = "ASSIGNED_ON";
        public static readonly string ColumnName_AssignedTo = "ASSIGNED_TO";
        public static readonly string ColumnName_Message = "MESSAGE";
        public static readonly string ColumnName_IsRead = "IS_READ";

        public static readonly string TableStruct = "(" + ColumnName_Id + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                                                        + ColumnName_AssignedBy + " INTEGER, "
                                                        + ColumnName_AssignedOn + " TIMESTAMP, "
                                                        + ColumnName_AssignedTo + " INTEGER, "
                                                        + ColumnName_Message + " VARCHAR2(4000), "
                                                        + ColumnName_IsRead + " NUMBER(1))";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
