namespace Wexflow.Core.Db.Oracle
{
    public class User : Core.Db.User
    {
        public const string COLUMN_NAME_ID = "ID";
        public const string COLUMN_NAME_USERNAME = "USERNAME";
        public const string COLUMN_NAME_PASSWORD = "PASSWORD";
        public const string COLUMN_NAME_USER_PROFILE = "USER_PROFILE";
        public const string COLUMN_NAME_EMAIL = "EMAIL";
        public const string COLUMN_NAME_CREATED_ON = "CREATED_ON";
        public const string COLUMN_NAME_MODIFIED_ON = "MODIFIED_ON";

        public const string TABLE_STRUCT = "(" + COLUMN_NAME_ID + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + COLUMN_NAME_USERNAME + " VARCHAR2(255), " + COLUMN_NAME_PASSWORD + " VARCHAR2(255), " + COLUMN_NAME_USER_PROFILE + " INTEGER, " + COLUMN_NAME_EMAIL + " VARCHAR2(255), " + COLUMN_NAME_CREATED_ON + " TIMESTAMP, " + COLUMN_NAME_MODIFIED_ON + " TIMESTAMP)";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
