namespace Wexflow.Core.Db.Oracle
{
    public class UserWorkflow : Core.Db.UserWorkflow
    {
        public static readonly string ColumnName_Id = "ID";
        public static readonly string ColumnName_UserId = "USER_ID";
        public static readonly string ColumnName_WorkflowId = "WORKFLOW_ID";

        public static readonly string TableStruct = "(" + ColumnName_Id + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + ColumnName_UserId + " INTEGER, " + ColumnName_WorkflowId + " INTEGER)";

        public string Id { get; set; }
    }
}
