namespace Wexflow.Core.Db.Oracle
{
    public class User : Core.Db.User
    {
        public const string ColumnNameId = "ID";
        public const string ColumnNameUsername = "USERNAME";
        public const string ColumnNamePassword = "PASSWORD";
        public const string ColumnNameUserProfile = "USER_PROFILE";
        public const string ColumnNameEmail = "EMAIL";
        public const string ColumnNameCreatedOn = "CREATED_ON";
        public const string ColumnNameModifiedOn = "MODIFIED_ON";

        public const string TableStruct = "(" + ColumnNameId + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + ColumnNameUsername + " VARCHAR2(255), " + ColumnNamePassword + " VARCHAR2(255), " + ColumnNameUserProfile + " INTEGER, " + ColumnNameEmail + " VARCHAR2(255), " + ColumnNameCreatedOn + " TIMESTAMP, " + ColumnNameModifiedOn + " TIMESTAMP)";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
