namespace Wexflow.Core.Db.Oracle
{
    public class Workflow : Core.Db.Workflow
    {
        public const string ColumnNameId = "ID";
        public const string ColumnNameXml = "XML";

        public const string TableStruct = "(" + ColumnNameId + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + ColumnNameXml + " CLOB)";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
