namespace Wexflow.Core.Db.Oracle
{
    public class Workflow : Core.Db.Workflow
    {
        public static readonly string ColumnName_Id = "ID";
        public static readonly string ColumnName_Xml = "XML";

        public static readonly string TableStruct = "(" + ColumnName_Id + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + ColumnName_Xml + " CLOB)";

        public long Id { get; set; }

        public override string GetDbId()
        {
            return Id.ToString();
        }
    }
}
